//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaysDBApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailwaysDBApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The train must have at least one carriage.
        /// </summary>
        internal static string AddTrain_CarriagesNeeded {
            get {
                return ResourceManager.GetString("AddTrain_CarriagesNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carriages of type {0}.
        /// </summary>
        internal static string AddTrain_CarriagesOfType {
            get {
                return ResourceManager.GetString("AddTrain_CarriagesOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find path.
        /// </summary>
        internal static string AddTrain_FindPath {
            get {
                return ResourceManager.GetString("AddTrain_FindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From:.
        /// </summary>
        internal static string AddTrain_From {
            get {
                return ResourceManager.GetString("AddTrain_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding the train.
        /// </summary>
        internal static string AddTrain_Name {
            get {
                return ResourceManager.GetString("AddTrain_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured while adding train.
        /// </summary>
        internal static string AddTrain_ProblemsAddingTrain {
            get {
                return ResourceManager.GetString("AddTrain_ProblemsAddingTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register train.
        /// </summary>
        internal static string AddTrain_RegisterTrain {
            get {
                return ResourceManager.GetString("AddTrain_RegisterTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stations on the way.
        /// </summary>
        internal static string AddTrain_StationsOnTheWay {
            get {
                return ResourceManager.GetString("AddTrain_StationsOnTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop time.
        /// </summary>
        internal static string AddTrain_StopTime {
            get {
                return ResourceManager.GetString("AddTrain_StopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The train has been added successfully.
        /// </summary>
        internal static string AddTrain_SuccessfullyAdded {
            get {
                return ResourceManager.GetString("AddTrain_SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To:.
        /// </summary>
        internal static string AddTrain_To {
            get {
                return ResourceManager.GetString("AddTrain_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of train.
        /// </summary>
        internal static string AddTrain_TrainType {
            get {
                return ResourceManager.GetString("AddTrain_TrainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fast.
        /// </summary>
        internal static string AddTrain_TrainType_fast {
            get {
                return ResourceManager.GetString("AddTrain_TrainType_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High speed.
        /// </summary>
        internal static string AddTrain_TrainType_high {
            get {
                return ResourceManager.GetString("AddTrain_TrainType_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intercity.
        /// </summary>
        internal static string AddTrain_TrainType_inter {
            get {
                return ResourceManager.GetString("AddTrain_TrainType_inter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Usual.
        /// </summary>
        internal static string AddTrain_TrainType_usual {
            get {
                return ResourceManager.GetString("AddTrain_TrainType_usual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add user.
        /// </summary>
        internal static string AddUser_AddUser {
            get {
                return ResourceManager.GetString("AddUser_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrator.
        /// </summary>
        internal static string AddUser_admin {
            get {
                return ResourceManager.GetString("AddUser_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attempt to add user failed.
        /// </summary>
        internal static string AddUser_Fail {
            get {
                return ResourceManager.GetString("AddUser_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login:.
        /// </summary>
        internal static string AddUser_Login {
            get {
                return ResourceManager.GetString("AddUser_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager.
        /// </summary>
        internal static string AddUser_manager {
            get {
                return ResourceManager.GetString("AddUser_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding user.
        /// </summary>
        internal static string AddUser_Name {
            get {
                return ResourceManager.GetString("AddUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all fields are filled.
        /// </summary>
        internal static string AddUser_NonAllFields {
            get {
                return ResourceManager.GetString("AddUser_NonAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        internal static string AddUser_Password {
            get {
                return ResourceManager.GetString("AddUser_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords don`t match.
        /// </summary>
        internal static string AddUser_PasswordsEqual {
            get {
                return ResourceManager.GetString("AddUser_PasswordsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission:.
        /// </summary>
        internal static string AddUser_Permission {
            get {
                return ResourceManager.GetString("AddUser_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password:.
        /// </summary>
        internal static string AddUser_RepeatPassword {
            get {
                return ResourceManager.GetString("AddUser_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User succesfully registered.
        /// </summary>
        internal static string AddUser_Success {
            get {
                return ResourceManager.GetString("AddUser_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        internal static string AddUser_user {
            get {
                return ResourceManager.GetString("AddUser_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User with the same name already exists.
        /// </summary>
        internal static string AddUser_UserExists {
            get {
                return ResourceManager.GetString("AddUser_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appropriate races.
        /// </summary>
        internal static string BuyTicket_AppropriateRaces {
            get {
                return ResourceManager.GetString("BuyTicket_AppropriateRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy.
        /// </summary>
        internal static string BuyTicket_Buy {
            get {
                return ResourceManager.GetString("BuyTicket_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carriage.
        /// </summary>
        internal static string BuyTicket_Carriage {
            get {
                return ResourceManager.GetString("BuyTicket_Carriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carriage number.
        /// </summary>
        internal static string BuyTicket_CarriageNumber {
            get {
                return ResourceManager.GetString("BuyTicket_CarriageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carriage type.
        /// </summary>
        internal static string BuyTicket_CarriageType {
            get {
                return ResourceManager.GetString("BuyTicket_CarriageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compartment.
        /// </summary>
        internal static string BuyTicket_CarriageType_CP {
            get {
                return ResourceManager.GetString("BuyTicket_CarriageType_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reserved seat.
        /// </summary>
        internal static string BuyTicket_CarriageType_PK {
            get {
                return ResourceManager.GetString("BuyTicket_CarriageType_PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sleeping compartment.
        /// </summary>
        internal static string BuyTicket_CarriageType_SV {
            get {
                return ResourceManager.GetString("BuyTicket_CarriageType_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose the date.
        /// </summary>
        internal static string BuyTicket_ChooseDate {
            get {
                return ResourceManager.GetString("BuyTicket_ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string BuyTicket_Date {
            get {
                return ResourceManager.GetString("BuyTicket_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stations must be different.
        /// </summary>
        internal static string BuyTicket_DifferentStations {
            get {
                return ResourceManager.GetString("BuyTicket_DifferentStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured while completing operation.
        /// </summary>
        internal static string BuyTicket_Error {
            get {
                return ResourceManager.GetString("BuyTicket_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find.
        /// </summary>
        internal static string BuyTicket_FindRaces {
            get {
                return ResourceManager.GetString("BuyTicket_FindRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} ({1} free places).
        /// </summary>
        internal static string BuyTicket_FreePlaces {
            get {
                return ResourceManager.GetString("BuyTicket_FreePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        internal static string BuyTicket_From {
            get {
                return ResourceManager.GetString("BuyTicket_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy ticket.
        /// </summary>
        internal static string BuyTicket_Name {
            get {
                return ResourceManager.GetString("BuyTicket_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No appropriate races.
        /// </summary>
        internal static string BuyTicket_NoAppropriateRaces {
            get {
                return ResourceManager.GetString("BuyTicket_NoAppropriateRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No free carriages.
        /// </summary>
        internal static string BuyTicket_NoFreeCarriages {
            get {
                return ResourceManager.GetString("BuyTicket_NoFreeCarriages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Off time.
        /// </summary>
        internal static string BuyTicket_OffTime {
            get {
                return ResourceManager.GetString("BuyTicket_OffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On time.
        /// </summary>
        internal static string BuyTicket_OnTime {
            get {
                return ResourceManager.GetString("BuyTicket_OnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Place.
        /// </summary>
        internal static string BuyTicket_Place {
            get {
                return ResourceManager.GetString("BuyTicket_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Place number.
        /// </summary>
        internal static string BuyTicket_PlaceNumber {
            get {
                return ResourceManager.GetString("BuyTicket_PlaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        internal static string BuyTicket_Price {
            get {
                return ResourceManager.GetString("BuyTicket_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train number: {0} - {1} (departure from {2} at {3}) - (arrival to {4} at {5}) {6}.
        /// </summary>
        internal static string BuyTicket_Race {
            get {
                return ResourceManager.GetString("BuyTicket_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation successfull.
        /// </summary>
        internal static string BuyTicket_Success {
            get {
                return ResourceManager.GetString("BuyTicket_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To.
        /// </summary>
        internal static string BuyTicket_To {
            get {
                return ResourceManager.GetString("BuyTicket_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train #.
        /// </summary>
        internal static string BuyTicket_TrainId {
            get {
                return ResourceManager.GetString("BuyTicket_TrainId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types of carriages.
        /// </summary>
        internal static string CARRIAGE_TYPE {
            get {
                return ResourceManager.GetString("CARRIAGE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of the carriage type.
        /// </summary>
        internal static string CARRIAGE_TYPE_ID {
            get {
                return ResourceManager.GetString("CARRIAGE_TYPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of the carriage type.
        /// </summary>
        internal static string CARRIAGE_TYPE_NAME {
            get {
                return ResourceManager.GetString("CARRIAGE_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of places.
        /// </summary>
        internal static string CARRIAGE_TYPE_PLACES {
            get {
                return ResourceManager.GetString("CARRIAGE_TYPE_PLACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price multiplier.
        /// </summary>
        internal static string CARRIAGE_TYPE_PRICE_MULTIPLIER {
            get {
                return ResourceManager.GetString("CARRIAGE_TYPE_PRICE_MULTIPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carriages.
        /// </summary>
        internal static string CARRIAGES {
            get {
                return ResourceManager.GetString("CARRIAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount included into train.
        /// </summary>
        internal static string CARRIAGES_AMOUNT {
            get {
                return ResourceManager.GetString("CARRIAGES_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of the type of the carriage.
        /// </summary>
        internal static string CARRIAGES_CARRIAGE_TYPE_ID {
            get {
                return ResourceManager.GetString("CARRIAGES_CARRIAGE_TYPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carriage id.
        /// </summary>
        internal static string CARRIAGES_ID {
            get {
                return ResourceManager.GetString("CARRIAGES_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of corresponding train.
        /// </summary>
        internal static string CARRIAGES_TRAIN_ID {
            get {
                return ResourceManager.GetString("CARRIAGES_TRAIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Railroad connections.
        /// </summary>
        internal static string EDGES {
            get {
                return ResourceManager.GetString("EDGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of finishing station.
        /// </summary>
        internal static string EDGES_FIN_ID {
            get {
                return ResourceManager.GetString("EDGES_FIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of the edge.
        /// </summary>
        internal static string EDGES_ID {
            get {
                return ResourceManager.GetString("EDGES_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pass price.
        /// </summary>
        internal static string EDGES_PASS_PRICE {
            get {
                return ResourceManager.GetString("EDGES_PASS_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time needed to pass.
        /// </summary>
        internal static string EDGES_PASS_TIME {
            get {
                return ResourceManager.GetString("EDGES_PASS_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of starting station.
        /// </summary>
        internal static string EDGES_START_ID {
            get {
                return ResourceManager.GetString("EDGES_START_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To delete records select them and press delet on keyboard.
        /// </summary>
        internal static string EditDBWindow_DeleteHint {
            get {
                return ResourceManager.GetString("EditDBWindow_DeleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit DB tables.
        /// </summary>
        internal static string EditDBWindow_Name {
            get {
                return ResourceManager.GetString("EditDBWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add user.
        /// </summary>
        internal static string MainMenu_AddUser {
            get {
                return ResourceManager.GetString("MainMenu_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy a ticket.
        /// </summary>
        internal static string MainMenu_BuyTicket {
            get {
                return ResourceManager.GetString("MainMenu_BuyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change user.
        /// </summary>
        internal static string MainMenu_ChangeUser {
            get {
                return ResourceManager.GetString("MainMenu_ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit DB tables.
        /// </summary>
        internal static string MainMenu_EditTables {
            get {
                return ResourceManager.GetString("MainMenu_EditTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main menu.
        /// </summary>
        internal static string MainMenu_Name {
            get {
                return ResourceManager.GetString("MainMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute queries.
        /// </summary>
        internal static string MainMenu_Queries {
            get {
                return ResourceManager.GetString("MainMenu_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reports.
        /// </summary>
        internal static string MainMenu_Reports {
            get {
                return ResourceManager.GetString("MainMenu_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit routes.
        /// </summary>
        internal static string MainMenu_Routes {
            get {
                return ResourceManager.GetString("MainMenu_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string MainMenu_Settings {
            get {
                return ResourceManager.GetString("MainMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go.
        /// </summary>
        internal static string MainWindow_Go {
            get {
                return ResourceManager.GetString("MainWindow_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login:.
        /// </summary>
        internal static string MainWindow_Login {
            get {
                return ResourceManager.GetString("MainWindow_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect login or password.
        /// </summary>
        internal static string MainWindow_LoginFault {
            get {
                return ResourceManager.GetString("MainWindow_LoginFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Railways.
        /// </summary>
        internal static string MainWindow_Name {
            get {
                return ResourceManager.GetString("MainWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        internal static string MainWindow_Password {
            get {
                return ResourceManager.GetString("MainWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adjacent stations.
        /// </summary>
        internal static string Queries_AdjacentStations {
            get {
                return ResourceManager.GetString("Queries_AdjacentStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Boarding stat. name.
        /// </summary>
        internal static string Queries_BoardingCityName {
            get {
                return ResourceManager.GetString("Queries_BoardingCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carriages of trains.
        /// </summary>
        internal static string Queries_CarriageOfTrains {
            get {
                return ResourceManager.GetString("Queries_CarriageOfTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City {0} doesn`t exist.
        /// </summary>
        internal static string Queries_CityNotExist {
            get {
                return ResourceManager.GetString("Queries_CityNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish station.
        /// </summary>
        internal static string Queries_FinishCity {
            get {
                return ResourceManager.GetString("Queries_FinishCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input a number.
        /// </summary>
        internal static string Queries_InputANumber {
            get {
                return ResourceManager.GetString("Queries_InputANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queries.
        /// </summary>
        internal static string Queries_Name {
            get {
                return ResourceManager.GetString("Queries_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Query`s result is empty.
        /// </summary>
        internal static string Queries_NoResult {
            get {
                return ResourceManager.GetString("Queries_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Races for train.
        /// </summary>
        internal static string Queries_RacesForTrain {
            get {
                return ResourceManager.GetString("Queries_RacesForTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find races through.
        /// </summary>
        internal static string Queries_RacesThrough {
            get {
                return ResourceManager.GetString("Queries_RacesThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting station.
        /// </summary>
        internal static string Queries_StartCity {
            get {
                return ResourceManager.GetString("Queries_StartCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Station name.
        /// </summary>
        internal static string Queries_StationName {
            get {
                return ResourceManager.GetString("Queries_StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ticket price.
        /// </summary>
        internal static string Queries_TicketPrice {
            get {
                return ResourceManager.GetString("Queries_TicketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tickets for race.
        /// </summary>
        internal static string Queries_TicketsForRace {
            get {
                return ResourceManager.GetString("Queries_TicketsForRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trains` destinations.
        /// </summary>
        internal static string Queries_TrainsDestinations {
            get {
                return ResourceManager.GetString("Queries_TrainsDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trains through station.
        /// </summary>
        internal static string Queries_TrainsThroughStation {
            get {
                return ResourceManager.GetString("Queries_TrainsThroughStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Races of trains.
        /// </summary>
        internal static string RACES {
            get {
                return ResourceManager.GetString("RACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Direction(0-from 1st stat., 1-from last).
        /// </summary>
        internal static string RACES_FORWARD {
            get {
                return ResourceManager.GetString("RACES_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of the race.
        /// </summary>
        internal static string RACES_ID {
            get {
                return ResourceManager.GetString("RACES_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date and time of departure.
        /// </summary>
        internal static string RACES_START_TIME {
            get {
                return ResourceManager.GetString("RACES_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of the train of the race.
        /// </summary>
        internal static string RACES_TRAIN_ID {
            get {
                return ResourceManager.GetString("RACES_TRAIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rails {
            get {
                object obj = ResourceManager.GetObject("rails", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reports.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings_Name {
            get {
                return ResourceManager.GetString("Settings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stations.
        /// </summary>
        internal static string STATIONS {
            get {
                return ResourceManager.GetString("STATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of the station.
        /// </summary>
        internal static string STATIONS_ID {
            get {
                return ResourceManager.GetString("STATIONS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of the station.
        /// </summary>
        internal static string STATIONS_NAME {
            get {
                return ResourceManager.GetString("STATIONS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stops.
        /// </summary>
        internal static string STOPS {
            get {
                return ResourceManager.GetString("STOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id of the stop.
        /// </summary>
        internal static string STOPS_ID {
            get {
                return ResourceManager.GetString("STOPS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pause time.
        /// </summary>
        internal static string STOPS_PAUSE_TIME {
            get {
                return ResourceManager.GetString("STOPS_PAUSE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Station id.
        /// </summary>
        internal static string STOPS_STATION_ID {
            get {
                return ResourceManager.GetString("STOPS_STATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of the stop for train.
        /// </summary>
        internal static string STOPS_STOP_NUMBER {
            get {
                return ResourceManager.GetString("STOPS_STOP_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train id.
        /// </summary>
        internal static string STOPS_TRAIN_ID {
            get {
                return ResourceManager.GetString("STOPS_TRAIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sold tickets.
        /// </summary>
        internal static string TICKETS {
            get {
                return ResourceManager.GetString("TICKETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carriage.
        /// </summary>
        internal static string TICKETS_CARRIAGE_NUMBER {
            get {
                return ResourceManager.GetString("TICKETS_CARRIAGE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of unboarding station.
        /// </summary>
        internal static string TICKETS_FIN_STATION_NUMBER {
            get {
                return ResourceManager.GetString("TICKETS_FIN_STATION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ticket id.
        /// </summary>
        internal static string TICKETS_ID {
            get {
                return ResourceManager.GetString("TICKETS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Place.
        /// </summary>
        internal static string TICKETS_PLACE_NUMBER {
            get {
                return ResourceManager.GetString("TICKETS_PLACE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Race id.
        /// </summary>
        internal static string TICKETS_RACE_ID {
            get {
                return ResourceManager.GetString("TICKETS_RACE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of boarding station.
        /// </summary>
        internal static string TICKETS_START_STATION_NUMBER {
            get {
                return ResourceManager.GetString("TICKETS_START_STATION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types of trains.
        /// </summary>
        internal static string TRAIN_TYPE {
            get {
                return ResourceManager.GetString("TRAIN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train type id.
        /// </summary>
        internal static string TRAIN_TYPE_ID {
            get {
                return ResourceManager.GetString("TRAIN_TYPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train type name.
        /// </summary>
        internal static string TRAIN_TYPE_NAME {
            get {
                return ResourceManager.GetString("TRAIN_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price multiplier.
        /// </summary>
        internal static string TRAIN_TYPE_PRICE_MULTIPLIER {
            get {
                return ResourceManager.GetString("TRAIN_TYPE_PRICE_MULTIPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed multiplier.
        /// </summary>
        internal static string TRAIN_TYPE_SPEED_MULTIPLIER {
            get {
                return ResourceManager.GetString("TRAIN_TYPE_SPEED_MULTIPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trains.
        /// </summary>
        internal static string TRAINS {
            get {
                return ResourceManager.GetString("TRAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End station #2.
        /// </summary>
        internal static string TRAINS_FINISH {
            get {
                return ResourceManager.GetString("TRAINS_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train id.
        /// </summary>
        internal static string TRAINS_ID {
            get {
                return ResourceManager.GetString("TRAINS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End station #1.
        /// </summary>
        internal static string TRAINS_START {
            get {
                return ResourceManager.GetString("TRAINS_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train type id.
        /// </summary>
        internal static string TRAINS_TRAIN_TYPE_ID {
            get {
                return ResourceManager.GetString("TRAINS_TRAIN_TYPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ukrzaliznytsya {
            get {
                object obj = ResourceManager.GetObject("ukrzaliznytsya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
